title: 💡 gedankenbrut
# email: your-email@example.com
# description: "A personal site powered by YAT"
# baseurl: "" # for user sites
url: "https://gedankenbrut.de"

remote_theme: jeffreytse/jekyll-theme-yat
plugins:
  - jekyll-remote-theme
  - jekyll-feed

yat:
  date_format: "%Y-%m-%d"
  show_excerpts: true
